config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get  '/settings',  to: 'static#settings'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :models
  resources :manufacturers
  resources :customers
  resources :vendors
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/customer.rb
class Customer < ApplicationRecord

  validates :name,        presence: true,
                          length: { maximum: 50 }

  validates :maxsip_id,   presence: true,
                          uniqueness: true

end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord

  has_many :Models, dependent: :destroy

  validates :name,    presence: true,
                      length: { maximum: 50 },
                      uniqueness: true

end

app/models/model.rb
class Model < ApplicationRecord

  belongs_to :manufacturer

  validates :name,   presence: true,
                     uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name,    presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,   presence:   true,
                      length: { maximum: 255 },
                      format:     { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/vendor.rb
class Vendor < ApplicationRecord

  validates :name,  presence: true,
                    uniqueness: true

end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @title = 'All Models'
    @models = Model.order(:name)
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @title = @model.name
  end

  # GET /models/new
  def new
    @title = 'New Model'
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
    @title = 'Edit ' + @model.name
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to models_url, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to models_url, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :manufacturer_id)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.haml
= form_with(model: model, local: true) do |form|
  - if model.errors.any?
    #error_explanation
      %h2
        = pluralize(model.errors.count, "error")
        prohibited this model from being saved:
      %ul
        - model.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :name
    = form.text_field :name, id: :model_name, class: 'form-control'
  .form-group
    = form.label :manufacturer_id
    = form.collection_select :manufacturer_id, Manufacturer.all, :id, :name,{include_blank: 'Pick one...'}, { class: 'form-control' }
  = form.submit class: 'btn btn-primary'

app/views/models/edit.haml
= render 'form', model: @model

app/views/models/index.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Manufacturer
        %th{:colspan => "3"}
    %tbody
      - @models.each do |model|
        %tr
          %td= link_to model.name, model
          %td= link_to model.manufacturer.name, model
          %td.actions
            = link_to 'Edit', edit_model_path(model), class: 'btn btn-primary'
            = link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
= link_to 'New Model', new_model_path, class: 'btn btn-primary'

app/views/models/new.haml
= render 'form', model: @model

app/views/models/show.haml
%p
  %strong Name:
  = @model.name
%p
  %strong Manufacturer:
  = @model.manufacturer.name

.actions
  = link_to 'Edit', edit_model_path(@model)
  = link_to 'Back', models_path