config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get  '/settings',  to: 'static#settings'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :models
  resources :manufacturers
  resources :customers
  resources :vendors
  resources :users

end

app/models/vendor.rb
class Vendor < ApplicationRecord

  validates :name,  presence: true,
                    uniqueness: true

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @title = 'All Vendors'
    @vendors = Vendor.order(:name)
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @title = @vendor.name
  end

  # GET /vendors/new
  def new
    @title = 'New Vendor'
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
    @title = 'Edit ' + @user.name
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendors_url, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendors_url, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.haml
= form_with(model: vendor, local: true) do |form|
  - if vendor.errors.any?
    #error_explanation
      %h2
        = pluralize(vendor.errors.count, "error")
        prohibited this vendor from being saved:
      %ul
        - vendor.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :name
    = form.text_field :name, id: :vendor_name, class: 'form-control'
  = form.submit class: 'btn btn-primary'

app/views/vendors/edit.haml
= render 'form', vendor: @vendor

app/views/vendors/index.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
    %tbody
      - @vendors.each do |vendor|
        %tr
          %td= link_to vendor.name, vendor
          %td.actions
            = link_to 'Edit', edit_vendor_path(vendor), class: 'btn btn-primary'
            = link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
= link_to 'New Vendor', new_vendor_path, class: 'btn btn-primary'

app/views/vendors/new.haml
= render 'form', vendor: @vendor

app/views/vendors/show.haml
%p
  %strong Name:
  = @vendor.name