config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get  '/settings',  to: 'static#settings'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :models
  resources :manufacturers
  resources :customers
  resources :vendors
  resources :users

end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Maxsip Inventory
    = csrf_meta_tags
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => "#"}
            %img{alt: 'Maxsip Logo', src: 'http://maxsip.com/img/maxsip.jpg', height: '20'}/


          -if logged_in?
            %ul.nav.navbar-nav
              %li= link_to 'Home', root_path
              %li= link_to 'Users', users_path
              %li= link_to 'Vendors', vendors_path
              %li= link_to 'Customers', customers_path
              %li= link_to 'Manufacturers', manufacturers_path
              %li= link_to 'Models', models_path
              %li= link_to 'Settings', settings_path

            %form.navbar-form.navbar-left{:role => "search"}
              .form-group
                %input.form-control{:placeholder => "Search", :type => "text"}/
              %button.btn.btn-default{:type => "submit"} Submit

            %p.navbar-text.navbar-right= link_to 'Log out', logout_path, method: :delete

    .container
    .page-header
      %h1= @title
      %ol.breadcrumb.inverse
        %li
          %a{:href => "#"} Home
        %li
          %a{:href => "#"} Library
        %li.active Data
      - flash.each do |type, message|
        .alert= message

      =yield


      %nav.text-center{ 'aria-label' => 'Page navigation'}
        %ul.pagination
          %li.disabled
            %a{'aria-label' => "Previous", href:'#'}
              %span{'aria-hidden' => "true"} «
          - (1..16).each do |i|
            %li.disabled
              %a{:href => "#"}= i
          %li.disabled
            %a{'aria-label' => 'Next', href:'#'}
              %span{'aria-hidden' => "true"} »